version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: thy015/test_ready/web
    container_name: tr_web
    ports:
      - "3000:3000"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: thy015/test_ready/server
    container_name: tr_server
    ports:
      - "4000:4000"
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: tr_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  mysql_data: