name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  styled_widget: ^0.4.1
  flutter_native_splash: ^2.4.6
  animated_bottom_navigation_bar: ^1.4.0
  introduction_screen: ^3.1.17
  ionicons: ^0.2.2
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  selectable: ^0.5.0
  dropdown_button2: ^2.3.9
  flutter_tts: ^3.8.5
  http: ^1.4.0
  flutter_riverpod: ^2.0.4
  intl: ^0.18.1
  audioplayers: ^6.5.0
  flip_card: ^0.7.0
  pin_code_fields: ^8.0.1
  stylish_bottom_bar: ^1.1.1
  modal_bottom_sheet: ^3.0.0
  just_audio: ^0.9.36
  url_launcher: ^6.2.5
  flutter_stripe: ^11.5.0
  flutter_launcher_icons: ^0.13.1
  fl_chart: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/animations/onboarding1.json
    - lib/assets/animations/onboarding2.json
    - lib/assets/animations/book.json
flutter_native_splash:
  color: "#ffffff"
  image: lib/assets/images/vjp.png
  android: true
  ios: true
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/vjp.png"
