import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import '../global.css'
import { Suspense } from 'react'
import Loading from './loading'
import Header from '@/components/partials/header'

// font config

const roboto = Roboto({
  variable: '--font-roboto',
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.variable} antialiased`}>
        <Suspense fallback={<Loading />}>
          <Header />
          {children}
        </Suspense>
      </body>
    </html>
  )
}
