import { TestCollection } from '@/types/tests'

export const testCollections: TestCollection[] = [
  {
    id: 'col1',
    name: 'TOEIC ETS 2024',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2024-01-15T08:00:00Z',
    test: [
      {
        id: 'test1',
        isActive: true,
        name: 'Test 1',
        timesUserTest: 12,
        testCollectionId: 'col1',
        parts: [
          {
            id: 'part1',
            name: 'p1',
            type: 'listening',
            total_question: 2,
            end_time: 2.28,
            questions: [
              {
                id: 'q1_p1_1',
                testId: 'test1',
                partId: 'part1',
                content: 'What is the man doing in the picture?',
                imgSrc:
                  'https://res.cloudinary.com/dqe8linji/image/upload/v1749198572/Screenshot_2025-06-06_152711_vslnt8.png',
                explanation: 'The man is opening the car.',
                correctAnswer: 'a',
                answers: JSON.stringify({
                  a: 'He is opening the car',
                  b: 'He is reading a book',
                  c: 'He is cooking food',
                  d: 'He is washing dishes',
                }),
                score: 5,
                start_time: 1.37,
              },
              {
                id: 'q1_p1_2',
                testId: 'test1',
                partId: 'part1',
                content: 'Where is the woman standing?',
                imgSrc:
                  'https://res.cloudinary.com/dqe8linji/image/upload/v1749198568/Screenshot_2025-06-06_152718_yiegff.png',
                explanation: 'The woman is standing next to a car.',
                correctAnswer: 'b',
                answers: JSON.stringify({
                  a: 'In front of a building',
                  b: 'Next to a car',
                  c: 'Behind a tree',
                  d: 'On a bridge',
                }),
                score: 5,
                start_time: 2.04,
              },
            ],
          },
          {
            id: 'part2',
            name: 'p2',
            type: 'listening',
            total_question: 25,
            end_time: 30.0,
            questions: [
              {
                id: 'q1_p2_1',
                testId: 'test1',
                partId: 'part2',
                content: 'What is the main topic of the conversation?',
                imgSrc: '',
                explanation: 'The main topic is about a project deadline.',
                correctAnswer: 'c',
                answers: JSON.stringify({
                  a: 'A personal issue',
                  b: 'A vacation plan',
                  c: 'A project deadline',
                  d: 'A meeting schedule',
                }),
                score: 5,
                start_time: 3.02,
              },
              // Add more questions as needed
            ],
          },
          {
            id: 'part3',
            name: 'p3',
            type: 'listening',
            total_question: 39,
            end_time: 45.0,
          },
          {
            id: 'part4',
            name: 'p4',
            type: 'listening',
            total_question: 30,
            end_time: 30.0,
          },
          {
            id: 'part5',
            name: 'p5',
            type: 'reading',
            total_question: 30,
            end_time: 30.0,
          },
          {
            id: 'part6',
            name: 'p6',
            type: 'reading',
            total_question: 16,
            end_time: 20.0,
          },
          {
            id: 'part7',
            name: 'p7',
            type: 'reading' ,
            total_question: 54,
            end_time: 55.0,
          },
        ],
      },
      {
        id: 'test2',
        isActive: true,
        name: 'Test 2',
        testCollectionId: 'col1',
        timesUserTest: 245,
      },
      {
        id: 'ni',
        isActive: true,
        name: 'Test 3',
        testCollectionId: 'col1',
        timesUserTest: 245,
      },
      {
        id: 'nihon',
        isActive: true,
        name: 'Test 4',
        testCollectionId: 'col1',
        timesUserTest: 245,
      },
      {
        id: 'nihongo',
        isActive: true,
        name: 'Test 5',
        testCollectionId: 'col1',
        timesUserTest: 245,
      },
    ],
  },
  {
    id: 'col2',
    name: 'TOEIC ETS 2023',
    createdAt: '2023-12-20T08:00:00Z',
    updatedAt: '2024-01-05T08:00:00Z',
    test: [
      {
        id: 'test3',
        isActive: true,
        name: 'Test 1',
        testCollectionId: 'col2',
        timesUserTest: 111,
      },
      {
        id: 'test4',
        isActive: true,
        name: 'Test 2',
        testCollectionId: 'col2',
        timesUserTest: 120,
      },
    ],
  },
  {
    id: 'col3',
    name: 'Hacker TOEIC 3',
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-02-10T08:00:00Z',

    test: [
      {
        id: 'test6',
        isActive: true,
        name: 'Test 1',
        testCollectionId: 'col3',
        timesUserTest: 1222,
      },
      {
        id: 'test7',
        isActive: true,
        name: 'Test 2',
        testCollectionId: 'col3',
        timesUserTest: 8,
      },
      {
        id: 'test8',
        isActive: true,
        name: 'Test 3',
        testCollectionId: 'col3',
        timesUserTest: 887,
      },
    ],
  },
  {
    id: 'col4',
    name: 'TOEIC ETS 2022',
    createdAt: '2023-10-01T08:00:00Z',
    updatedAt: '2024-01-20T08:00:00Z',

    test: [
      {
        id: 'test9',
        isActive: true,
        name: 'Test 1',
        testCollectionId: 'col4',
        timesUserTest: 121,
      },
      {
        id: 'test10',
        isActive: true,
        name: 'Test 2',
        testCollectionId: 'col4',
        timesUserTest: 42,
      },
    ],
  },
]
